version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: JO.dockerfile
    container_name: node_app
    restart: always
    ports:
      - "3322:3000"
    volumes:
      - ./app:/app
    networks:
      - mynetwork

  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paris_olympics
      MYSQL_USER: paris
      MYSQL_PASSWORD: root
    ports:
      - "3316:3306"
    volumes:
      - ./test.sql:/docker-entrypoint-initdb.d/test.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
